### PR TITLE
fix compatibility issue with newer models

### PR DESCRIPTION
**Pull request by pilvar222**
based on https://platform.openai.com/docs/guides/gpt/chat-completions-vs-completions

### CODE REVIEW

**Comment by WhatTheFuzz** [comment]
Thanks for the PR! I will take a look tomorrow. Cheers!

**Review by WhatTheFuzz — APPROVED** [review]
Confirmed this works with openai version 0.28.0 and Binary Ninja 3.5.4516-dev.

**Comment by WhatTheFuzz** [comment]
Thanks again for the PR. I confirmed this works on the latest version of Binja and OpenAI. I don't get to mess around as much with Binja these days, so I apologize for the slow merge.

**Comment by pilvar222** [comment]
No worries, thanks for having taken a look into it :)

**Pull request merged**
